# Generated by Django 5.0.4 on 2024-04-18 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='office_staff_profiles/')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_one', models.CharField(max_length=20)),
                ('contact_two', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=700)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
