# Generated by Django 5.0.4 on 2024-04-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officestaff',
            name='new',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
