# Generated by Django 5.0.4 on 2024-04-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disha', '0002_officestaff_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officestaff',
            name='new',
        ),
    ]
